### ISSUE TITLE
Shapes that are partially outside the bounding box are not saved

### ISSUE THREAD

**Issue by vkotkas** [ambjsdp/CoCoViLa#49]

**Comment by vkotkas** [comment]
This seems to be not uniform. The feeling is that shapes loaded from package are included and the new ones that are partially outside of the upper-left corner of the bounding box are forgotten.

**Comment by vkotkas** [comment]
Answering No to the warning about leaving some shapes out results with an exception.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at ee.ioc.cs.vsle.classeditor.ClassEditor.saveToPackage(ClassEditor.java:1527)
	at ee.ioc.cs.vsle.classeditor.ClassEditor.exportShapesToPackage(ClassEditor.java:1380)
	at ee.ioc.cs.vsle.classeditor.EditorActionListener.actionPerformed(EditorActionListener.java:235)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
...

**Comment by vkotkas** [comment]
Ports outside the bounding box are always saved. Maybe this is desired - should be then explained in documentation.
