### ISSUE TITLE
Doubleclick on a port rises an exception

### ISSUE THREAD

**Issue by vkotkas** [ambjsdp/CoCoViLa#53]
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at ee.ioc.cs.vsle.classeditor.MouseOps.mouseClicked(MouseOps.java:492)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6528)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
...

**Comment by vkotkas** [comment]
When in adding ports mode right click on open area also adds a port - this is unexpected.

**Comment by AnnaMol** [comment]
The same for Text and Image shapes (right click issue)
I have assumed that was expected behavior. Fix for all?

**Comment by vkotkas** [comment]
For all the shapes left-click is for adding. I see no need to duplicate it with right-click. Typically, right-click is context dependent. Without a context (a shape on top of the click was made) it should either do nothing or reset to some preset mode.

**Comment by AnnaMol** [comment]
fixed w/ #56
